name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3
    - name: Check python syntax
      uses: cclauss/Find-Python-syntax-errors-action@v0.2.0